version: '3.6'

services:
  stellar-core-postgres:
    image: postgres:9
    restart: on-failure
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=stellar
      - POSTGRES_USER=stellar
      - POSTGRES_PASSWORD=changeme

  stellar-core-testnet:
    image: quay.io/openware/stellar:13.2.0
    restart: always
    volumes:
      - ./config/stellar-core-testnet.cfg:/stellar-core.cfg
      - ./data/testnet:/data
    environment:
      INITIALIZE_DB: "true"
      INITIALIZE_HISTORY_ARCHIVES: "true"
    ports:
    - 127.0.0.1:11625:11625
    - 127.0.0.1:11626:11626

  stellar-core-pubnet:
    image: quay.io/openware/stellar:13.2.0
    restart: always
    volumes:
      - ./config/stellar-core-pubnet.cfg:/stellar-core.cfg
      - ./data/pubnet:/data
    ports:
    - 127.0.0.1:11625:11625
    - 127.0.0.1:11626:11626

volumes:
  postgres_data:
